<?php

namespace App\Filament\Admin\Clusters\Area\Resources\Groups\Schemas;

use Filament\Forms\Components\DateTimePicker;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Schema;

class GroupForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('name')
                    ->required(),
                TextInput::make('sdLiteOnly')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('usesGoScan')
                    ->numeric()
                    ->default(0),
                TextInput::make('usesShop')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('usesPayFees')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('groupAccountID')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('scarf'),
                TextInput::make('groupTypeID')
                    ->required()
                    ->numeric(),
                Textarea::make('description')
                    ->columnSpanFull(),
                TextInput::make('multiDen')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('multiPack')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('multiTroop')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('multiCrew')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('meerkatProgramType')
                    ->required()
                    ->numeric()
                    ->default(1),
                TextInput::make('cubProgramType')
                    ->required()
                    ->numeric()
                    ->default(1),
                TextInput::make('scoutProgramType')
                    ->required()
                    ->numeric()
                    ->default(2),
                TextInput::make('roverProgramType')
                    ->required()
                    ->numeric()
                    ->default(1),
                TextInput::make('amsOnly')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('hasMeerkats')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('hasCubs')
                    ->numeric()
                    ->default(1),
                TextInput::make('hasScouts')
                    ->numeric()
                    ->default(1),
                TextInput::make('hasRovers')
                    ->numeric()
                    ->default(0),
                TextInput::make('hasBranch1')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('hasBranch2')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('hasBranch3')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('hasBranch4')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('hasBranch5')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('sendWeeklyMails')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('assoc_to_district')
                    ->required()
                    ->numeric(),
                TextInput::make('assoc_to_region')
                    ->required()
                    ->numeric(),
                TextInput::make('roverAssocToGroup')
                    ->numeric()
                    ->default(0),
                Textarea::make('phys_address')
                    ->columnSpanFull(),
                Textarea::make('postalAddress')
                    ->columnSpanFull(),
                TextInput::make('postalCountryID')
                    ->numeric()
                    ->default(196),
                TextInput::make('phys_country_id')
                    ->numeric()
                    ->default(196),
                Textarea::make('bankingDetails')
                    ->columnSpanFull(),
                TextInput::make('bankAccountName'),
                TextInput::make('bankName'),
                TextInput::make('branchName'),
                TextInput::make('branchCode'),
                TextInput::make('bankAccountNumber'),
                Textarea::make('invoiceNotes')
                    ->columnSpanFull(),
                TextInput::make('facebook'),
                TextInput::make('twitter'),
                TextInput::make('website')
                    ->url(),
                TextInput::make('email')
                    ->label('Email address')
                    ->email(),
                TextInput::make('googleplus'),
                TextInput::make('instagram'),
                TextInput::make('linkedin'),
                TextInput::make('pintrest'),
                TextInput::make('youtube'),
                TextInput::make('tumblr'),
                TextInput::make('googleMaps'),
                TextInput::make('gpsLat'),
                TextInput::make('gpsLon'),
                DateTimePicker::make('created')
                    ->required(),
                TextInput::make('createdby')
                    ->required()
                    ->numeric(),
                DateTimePicker::make('modified'),
                TextInput::make('modifiedby')
                    ->numeric(),
                TextInput::make('active')
                    ->required()
                    ->numeric(),
                TextInput::make('weatherID'),
                TextInput::make('weatherLocationName'),
                TextInput::make('managedRegionally')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canMoveToEntsha')
                    ->required()
                    ->numeric()
                    ->default(1),
                TextInput::make('using20')
                    ->required()
                    ->numeric()
                    ->default(1),
                TextInput::make('groupRegNr'),
                TextInput::make('censusDone')
                    ->numeric(),
                DateTimePicker::make('groupLastUpdated'),
                TextInput::make('groupLastUpdatedBy')
                    ->numeric(),
            ]);
    }
}
