<?php

namespace App\Filament\Admin\Resources\Users\Schemas;

use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class UserInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('oldID')
                    ->numeric(),
                TextEntry::make('username')
                    ->placeholder('-'),
                TextEntry::make('lastPasswordChange')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('lastLoginDate')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('startDate')
                    ->date()
                    ->placeholder('-'),
                TextEntry::make('title')
                    ->placeholder('-'),
                TextEntry::make('first_name')
                    ->placeholder('-'),
                TextEntry::make('otherName')
                    ->placeholder('-'),
                TextEntry::make('surname')
                    ->placeholder('-'),
                TextEntry::make('previousSurname')
                    ->placeholder('-'),
                TextEntry::make('knownName')
                    ->placeholder('-'),
                TextEntry::make('scoutName')
                    ->placeholder('-'),
                TextEntry::make('photo')
                    ->placeholder('-'),
                TextEntry::make('thumb')
                    ->placeholder('-'),
                TextEntry::make('idNumber')
                    ->placeholder('-'),
                TextEntry::make('IDBookLocation')
                    ->placeholder('-'),
                TextEntry::make('passportNumber')
                    ->placeholder('-'),
                TextEntry::make('passportCountry')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('partnersFullName')
                    ->placeholder('-'),
                TextEntry::make('sex')
                    ->placeholder('-'),
                TextEntry::make('race')
                    ->placeholder('-'),
                TextEntry::make('dob')
                    ->date()
                    ->placeholder('-'),
                TextEntry::make('dateInvested')
                    ->date()
                    ->placeholder('-'),
                TextEntry::make('multiID')
                    ->numeric(),
                TextEntry::make('packID')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('troopID')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('dateToCubs')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('dateToScouts')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('scoutPatrolID')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('scoutPatrolTaskID')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('dateToRovers')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('phys_address')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('gpsLat')
                    ->placeholder('-'),
                TextEntry::make('gpsLon')
                    ->placeholder('-'),
                TextEntry::make('gpsAccuracy')
                    ->placeholder('-'),
                TextEntry::make('phys_country_id')
                    ->numeric(),
                TextEntry::make('postal_address')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('postal_country_id')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('created')
                    ->dateTime(),
                TextEntry::make('createdby')
                    ->numeric(),
                TextEntry::make('modified')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('modifiedby')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('user_type')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('parentType')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('active')
                    ->numeric(),
                TextEntry::make('dateDeactivated')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('deactivatedBy')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('assoc_to_account')
                    ->numeric(),
                TextEntry::make('assoc_to_group')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('branch')
                    ->placeholder('-'),
                TextEntry::make('assoc_to_district')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('assoc_to_region')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('trainingRegionName')
                    ->placeholder('-'),
                TextEntry::make('trainingDistrictName')
                    ->placeholder('-'),
                TextEntry::make('trainingGroupName')
                    ->placeholder('-'),
                TextEntry::make('language')
                    ->placeholder('-'),
                TextEntry::make('cellNr')
                    ->placeholder('-'),
                TextEntry::make('officeNr')
                    ->placeholder('-'),
                TextEntry::make('homeNr')
                    ->placeholder('-'),
                TextEntry::make('faxNr')
                    ->placeholder('-'),
                TextEntry::make('responsible_for_payment')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('mustChangePassword')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('canLogon')
                    ->numeric(),
                TextEntry::make('medicalAidName')
                    ->placeholder('-'),
                TextEntry::make('medicalAidNr')
                    ->placeholder('-'),
                TextEntry::make('medicalAidPrincipalMember')
                    ->placeholder('-'),
                TextEntry::make('doctorsName')
                    ->placeholder('-'),
                TextEntry::make('doctorsPhone')
                    ->placeholder('-'),
                TextEntry::make('allergies')
                    ->placeholder('-'),
                TextEntry::make('allergiesInstructions')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('disabilities')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('disabilitiesInstructions')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('medicalConditions')
                    ->placeholder('-'),
                TextEntry::make('medicalConditionsInstructions')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('currentMedication')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('emergencyContactName')
                    ->placeholder('-'),
                TextEntry::make('emergencyContactCell')
                    ->placeholder('-'),
                TextEntry::make('emergencyContactTel')
                    ->placeholder('-'),
                TextEntry::make('emergencyContactRelationship')
                    ->placeholder('-'),
                TextEntry::make('specialMealRequirements')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('religiousAffilliation')
                    ->placeholder('-'),
                TextEntry::make('school')
                    ->placeholder('-'),
                TextEntry::make('religion')
                    ->placeholder('-'),
                TextEntry::make('religiousAffiliation')
                    ->placeholder('-'),
                TextEntry::make('hobbies')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('sports')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('interests')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('canAdmin')
                    ->numeric(),
                TextEntry::make('100CharID')
                    ->placeholder('-'),
                TextEntry::make('uniquePIN')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('weeklyEmailUnsubscribe')
                    ->numeric(),
                TextEntry::make('weeklyEmailUnsubscribeText')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('weeklyEmailUnsubscribeDate')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('logonEmailSent')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('LogonEmailDate')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('amsOnly')
                    ->numeric(),
                TextEntry::make('amsRole')
                    ->numeric(),
                TextEntry::make('homeLanguage')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('otherLanguage')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('otherLanguages')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('proficiencyInEnglish')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('religiousBelief')
                    ->placeholder('-'),
                TextEntry::make('highestEducation')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('nrOfChildrenBoys')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('nrOfChildrenGirls')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('occupation')
                    ->placeholder('-'),
                TextEntry::make('typeOfEmployment')
                    ->placeholder('-'),
                TextEntry::make('employer')
                    ->placeholder('-'),
                TextEntry::make('maritalStatus')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ref1Name')
                    ->placeholder('-'),
                TextEntry::make('ref1Address')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ref1Tel')
                    ->placeholder('-'),
                TextEntry::make('ref2Name')
                    ->placeholder('-'),
                TextEntry::make('ref2Address')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ref2Tel')
                    ->placeholder('-'),
                TextEntry::make('newsletterUnsubscribe')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('newsletterUnsubscribeDate')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('reportView')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('roverGroupID')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('roverGroupRoleID')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('roverGroupAccountID')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('24WSJ')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('24WSJRole')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('24wsjNotListedDistrict')
                    ->placeholder('-'),
                TextEntry::make('24wsjNotListedGroup')
                    ->placeholder('-'),
                TextEntry::make('SANJamb2017')
                    ->numeric(),
                TextEntry::make('SANJamb2017Role'),
                TextEntry::make('sanJambNotListedRegion')
                    ->placeholder('-'),
                TextEntry::make('sanJambNotListedDistrict')
                    ->placeholder('-'),
                TextEntry::make('sanJambNotListedGroup')
                    ->placeholder('-'),
                TextEntry::make('infoRedacted')
                    ->numeric(),
                TextEntry::make('SSANumber')
                    ->placeholder('-'),
                TextEntry::make('orphaned')
                    ->numeric(),
                TextEntry::make('vulnerable')
                    ->numeric(),
                TextEntry::make('sendAMSMail')
                    ->numeric(),
                TextEntry::make('generalNotes')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('form29Generated')
                    ->numeric(),
                TextEntry::make('logonEmail')
                    ->numeric(),
                TextEntry::make('weeklyProgramEmail')
                    ->numeric(),
                TextEntry::make('profileChangesEmail')
                    ->numeric(),
                TextEntry::make('newsletterEmail')
                    ->numeric(),
                TextEntry::make('lowerStaffProfileChanges')
                    ->numeric(),
                TextEntry::make('loggedInTo20')
                    ->numeric(),
                TextEntry::make('canLogonTo20')
                    ->numeric(),
                TextEntry::make('adultRecruit')
                    ->numeric(),
                TextEntry::make('addedIn')
                    ->numeric(),
                TextEntry::make('canAdminElearning')
                    ->numeric(),
                TextEntry::make('canAdminElearningCourses')
                    ->numeric(),
                TextEntry::make('view')
                    ->numeric(),
                TextEntry::make('docsDeleted')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('takenSurvey')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ddValue')
                    ->numeric(),
                TextEntry::make('DSDHostelName')
                    ->placeholder('-'),
                TextEntry::make('DSDTownshipName')
                    ->placeholder('-'),
                TextEntry::make('DSDDisabled')
                    ->numeric()
                    ->placeholder('-'),
            ]);
    }
}
