<?php

namespace App\Filament\Admin\Resources\Users\Schemas;

use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\DateTimePicker;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Schema;

class UserForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('oldID')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('username'),
                TextInput::make('passwordNew')
                    ->password(),
                DateTimePicker::make('lastPasswordChange'),
                TextInput::make('passwordChangedBy')
                    ->password()
                    ->numeric(),
                DateTimePicker::make('lastLoginDate'),
                DatePicker::make('startDate'),
                TextInput::make('title'),
                TextInput::make('first_name'),
                TextInput::make('otherName'),
                TextInput::make('surname'),
                TextInput::make('previousSurname'),
                TextInput::make('knownName'),
                TextInput::make('scoutName'),
                TextInput::make('photo'),
                TextInput::make('thumb'),
                TextInput::make('idNumber'),
                TextInput::make('IDBookLocation'),
                TextInput::make('passportNumber'),
                TextInput::make('passportCountry')
                    ->numeric()
                    ->default(196),
                TextInput::make('partnersFullName'),
                TextInput::make('sex'),
                TextInput::make('race'),
                DatePicker::make('dob'),
                DatePicker::make('dateInvested'),
                TextInput::make('multiID')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('packID')
                    ->numeric()
                    ->default(0),
                TextInput::make('troopID')
                    ->numeric()
                    ->default(0),
                DateTimePicker::make('dateToCubs'),
                DateTimePicker::make('dateToScouts'),
                TextInput::make('scoutPatrolID')
                    ->numeric(),
                TextInput::make('scoutPatrolTaskID')
                    ->numeric(),
                DateTimePicker::make('dateToRovers'),
                Textarea::make('phys_address')
                    ->columnSpanFull(),
                TextInput::make('gpsLat'),
                TextInput::make('gpsLon'),
                TextInput::make('gpsAccuracy'),
                TextInput::make('phys_country_id')
                    ->required()
                    ->numeric()
                    ->default(196),
                Textarea::make('postal_address')
                    ->columnSpanFull(),
                TextInput::make('postal_country_id')
                    ->numeric(),
                DateTimePicker::make('created')
                    ->required(),
                TextInput::make('createdby')
                    ->required()
                    ->numeric()
                    ->default(0),
                DateTimePicker::make('modified'),
                TextInput::make('modifiedby')
                    ->numeric(),
                TextInput::make('user_type')
                    ->numeric(),
                TextInput::make('parentType')
                    ->numeric(),
                TextInput::make('active')
                    ->required()
                    ->numeric(),
                DateTimePicker::make('dateDeactivated'),
                TextInput::make('deactivatedBy')
                    ->numeric(),
                TextInput::make('assoc_to_account')
                    ->required()
                    ->numeric(),
                TextInput::make('assoc_to_group')
                    ->numeric(),
                TextInput::make('branch'),
                TextInput::make('assoc_to_district')
                    ->numeric(),
                TextInput::make('assoc_to_region')
                    ->numeric(),
                TextInput::make('trainingRegionName'),
                TextInput::make('trainingDistrictName'),
                TextInput::make('trainingGroupName'),
                TextInput::make('language'),
                TextInput::make('cellNr'),
                TextInput::make('officeNr'),
                TextInput::make('homeNr'),
                TextInput::make('faxNr'),
                TextInput::make('responsible_for_payment')
                    ->numeric(),
                TextInput::make('mustChangePassword')
                    ->numeric(),
                TextInput::make('canLogon')
                    ->required()
                    ->numeric(),
                TextInput::make('medicalAidName'),
                TextInput::make('medicalAidNr'),
                TextInput::make('medicalAidPrincipalMember'),
                TextInput::make('doctorsName'),
                TextInput::make('doctorsPhone'),
                TextInput::make('allergies'),
                Textarea::make('allergiesInstructions')
                    ->columnSpanFull(),
                Textarea::make('disabilities')
                    ->columnSpanFull(),
                Textarea::make('disabilitiesInstructions')
                    ->columnSpanFull(),
                TextInput::make('medicalConditions'),
                Textarea::make('medicalConditionsInstructions')
                    ->columnSpanFull(),
                Textarea::make('currentMedication')
                    ->columnSpanFull(),
                TextInput::make('emergencyContactName'),
                TextInput::make('emergencyContactCell'),
                TextInput::make('emergencyContactTel'),
                TextInput::make('emergencyContactRelationship'),
                Textarea::make('specialMealRequirements')
                    ->columnSpanFull(),
                TextInput::make('religiousAffilliation'),
                TextInput::make('school'),
                TextInput::make('religion'),
                TextInput::make('religiousAffiliation'),
                Textarea::make('hobbies')
                    ->columnSpanFull(),
                Textarea::make('sports')
                    ->columnSpanFull(),
                Textarea::make('interests')
                    ->columnSpanFull(),
                TextInput::make('canAdmin')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('100CharID'),
                TextInput::make('uniquePIN')
                    ->numeric(),
                TextInput::make('weeklyEmailUnsubscribe')
                    ->required()
                    ->numeric()
                    ->default(0),
                Textarea::make('weeklyEmailUnsubscribeText')
                    ->columnSpanFull(),
                DateTimePicker::make('weeklyEmailUnsubscribeDate'),
                TextInput::make('logonEmailSent')
                    ->numeric(),
                DateTimePicker::make('LogonEmailDate'),
                TextInput::make('amsOnly')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('amsRole')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('homeLanguage')
                    ->numeric(),
                TextInput::make('otherLanguage')
                    ->numeric(),
                Textarea::make('otherLanguages')
                    ->columnSpanFull(),
                TextInput::make('proficiencyInEnglish')
                    ->numeric()
                    ->default(0),
                TextInput::make('religiousBelief'),
                TextInput::make('highestEducation')
                    ->numeric(),
                TextInput::make('nrOfChildrenBoys')
                    ->numeric(),
                TextInput::make('nrOfChildrenGirls')
                    ->numeric(),
                TextInput::make('occupation'),
                TextInput::make('typeOfEmployment'),
                TextInput::make('employer'),
                TextInput::make('maritalStatus')
                    ->numeric(),
                TextInput::make('ref1Name'),
                Textarea::make('ref1Address')
                    ->columnSpanFull(),
                TextInput::make('ref1Tel'),
                TextInput::make('ref2Name'),
                Textarea::make('ref2Address')
                    ->columnSpanFull(),
                TextInput::make('ref2Tel'),
                TextInput::make('newsletterUnsubscribe')
                    ->numeric()
                    ->default(0),
                DateTimePicker::make('newsletterUnsubscribeDate'),
                TextInput::make('reportView')
                    ->numeric()
                    ->default(10),
                TextInput::make('roverGroupID')
                    ->numeric()
                    ->default(0),
                TextInput::make('roverGroupRoleID')
                    ->numeric()
                    ->default(0),
                TextInput::make('roverGroupAccountID')
                    ->numeric()
                    ->default(0),
                TextInput::make('24WSJ')
                    ->numeric()
                    ->default(0),
                TextInput::make('24WSJRole')
                    ->numeric()
                    ->default(0),
                TextInput::make('24wsjNotListedDistrict'),
                TextInput::make('24wsjNotListedGroup'),
                TextInput::make('SANJamb2017')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('SANJamb2017Role')
                    ->required()
                    ->default('0'),
                TextInput::make('sanJambNotListedRegion'),
                TextInput::make('sanJambNotListedDistrict'),
                TextInput::make('sanJambNotListedGroup'),
                TextInput::make('infoRedacted')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('SSANumber'),
                TextInput::make('orphaned')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('vulnerable')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('sendAMSMail')
                    ->required()
                    ->numeric()
                    ->default(1),
                Textarea::make('generalNotes')
                    ->columnSpanFull(),
                TextInput::make('form29Generated')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('logonEmail')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('weeklyProgramEmail')
                    ->required()
                    ->numeric()
                    ->default(1),
                TextInput::make('profileChangesEmail')
                    ->required()
                    ->numeric()
                    ->default(1),
                TextInput::make('newsletterEmail')
                    ->required()
                    ->numeric()
                    ->default(1),
                TextInput::make('lowerStaffProfileChanges')
                    ->required()
                    ->numeric()
                    ->default(1),
                TextInput::make('loggedInTo20')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canLogonTo20')
                    ->required()
                    ->numeric()
                    ->default(1),
                TextInput::make('adultRecruit')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('addedIn')
                    ->required()
                    ->numeric()
                    ->default(1),
                TextInput::make('canAdminElearning')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canAdminElearningCourses')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('view')
                    ->required()
                    ->numeric()
                    ->default(1),
                TextInput::make('docsDeleted')
                    ->numeric(),
                TextInput::make('takenSurvey')
                    ->numeric()
                    ->default(0),
                TextInput::make('ddValue')
                    ->required()
                    ->numeric()
                    ->default(25),
                TextInput::make('DSDHostelName')
                    ->tel(),
                TextInput::make('DSDTownshipName'),
                TextInput::make('DSDDisabled')
                    ->numeric()
                    ->default(0),
            ]);
    }
}
