<?php

namespace App\Filament\Admin\Resources\SystemUserTypes\Tables;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\ViewAction;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

class SystemUserTypesTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('countryID')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('name')
                    ->searchable(),
                TextColumn::make('sysAdmin')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('nationalRole')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('regionalRole')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('superDistrictRole')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('districtRole')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('groupRole')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('denRole')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('packRole')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('troopRole')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('crewRole')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('adultLeaderRole')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('parentHelperRole')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('alumniRole')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('warrantedRole')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('appointmentRole')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('requiresCriminalClearance')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('signsLeft')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('signsRight')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('chargeRole')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('active')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('position')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('canAdminAlumni')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('canSeeAlumni')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('canAdminNational')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('canSeeNational')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('canAdminRegion')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('canSeeRegion')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('canAdminRegionKids')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('canAdminRegionTraining')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('canAdminSuperDistrict')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('canSeeSuperDistrict')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('canAdminDistrict')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('canSeeDistrict')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('canAdminDistrictKids')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('canAdminGroup')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('canSeeGroup')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('canAdminGroupAdults')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('canAwardGroupMeerkats')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('canAwardGroupCubs')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('canAwardGroupScouts')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('canAwardGroupRovers')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('canSeeSupport')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('canAdminSupport')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('canAddWarrants')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('canAdminProperty')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('canSignWarrants')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('canAdminForm29')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('canAdminPoliceClearance')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('created')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('createdby')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('modified')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('modifiedby')
                    ->numeric()
                    ->sortable(),
            ])
            ->filters([
                //
            ])
            ->recordActions([
                ViewAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([]),
            ]);
    }
}
