<?php

namespace App\Filament\Admin\Clusters\LocationHierarchy\Resources\Groups\Tables;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Actions\ViewAction;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

class GroupsTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('name')
                    ->searchable(),
                TextColumn::make('sdLiteOnly')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('usesGoScan')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('usesShop')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('usesPayFees')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('groupAccountID')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('scarf')
                    ->searchable(),
                TextColumn::make('groupTypeID')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('multiDen')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('multiPack')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('multiTroop')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('multiCrew')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('meerkatProgramType')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('cubProgramType')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('scoutProgramType')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('roverProgramType')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('amsOnly')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('hasMeerkats')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('hasCubs')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('hasScouts')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('hasRovers')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('hasBranch1')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('hasBranch2')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('hasBranch3')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('hasBranch4')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('hasBranch5')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('sendWeeklyMails')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('assoc_to_district')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('assoc_to_region')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('roverAssocToGroup')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('postalCountryID')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('phys_country_id')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('bankAccountName')
                    ->searchable(),
                TextColumn::make('bankName')
                    ->searchable(),
                TextColumn::make('branchName')
                    ->searchable(),
                TextColumn::make('branchCode')
                    ->searchable(),
                TextColumn::make('bankAccountNumber')
                    ->searchable(),
                TextColumn::make('facebook')
                    ->searchable(),
                TextColumn::make('twitter')
                    ->searchable(),
                TextColumn::make('website')
                    ->searchable(),
                TextColumn::make('email')
                    ->label('Email address')
                    ->searchable(),
                TextColumn::make('googleplus')
                    ->searchable(),
                TextColumn::make('instagram')
                    ->searchable(),
                TextColumn::make('linkedin')
                    ->searchable(),
                TextColumn::make('pintrest')
                    ->searchable(),
                TextColumn::make('youtube')
                    ->searchable(),
                TextColumn::make('tumblr')
                    ->searchable(),
                TextColumn::make('googleMaps')
                    ->searchable(),
                TextColumn::make('gpsLat')
                    ->searchable(),
                TextColumn::make('gpsLon')
                    ->searchable(),
                TextColumn::make('created')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('createdby')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('modified')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('modifiedby')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('active')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('weatherID')
                    ->searchable(),
                TextColumn::make('weatherLocationName')
                    ->searchable(),
                TextColumn::make('managedRegionally')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('canMoveToEntsha')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('using20')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('groupRegNr')
                    ->searchable(),
                TextColumn::make('censusDone')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('groupLastUpdated')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('groupLastUpdatedBy')
                    ->numeric()
                    ->sortable(),
            ])
            ->filters([
                //
            ])
            ->recordActions([
                ViewAction::make(),
                EditAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }
}
