<?php

namespace App\Filament\Admin\Clusters\LocationHierarchy\Resources\Groups\Schemas;

use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class GroupInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('name'),
                TextEntry::make('sdLiteOnly')
                    ->numeric(),
                TextEntry::make('usesGoScan')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('usesShop')
                    ->numeric(),
                TextEntry::make('usesPayFees')
                    ->numeric(),
                TextEntry::make('groupAccountID')
                    ->numeric(),
                TextEntry::make('scarf')
                    ->placeholder('-'),
                TextEntry::make('groupTypeID')
                    ->numeric(),
                TextEntry::make('description')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('multiDen')
                    ->numeric(),
                TextEntry::make('multiPack')
                    ->numeric(),
                TextEntry::make('multiTroop')
                    ->numeric(),
                TextEntry::make('multiCrew')
                    ->numeric(),
                TextEntry::make('meerkatProgramType')
                    ->numeric(),
                TextEntry::make('cubProgramType')
                    ->numeric(),
                TextEntry::make('scoutProgramType')
                    ->numeric(),
                TextEntry::make('roverProgramType')
                    ->numeric(),
                TextEntry::make('amsOnly')
                    ->numeric(),
                TextEntry::make('hasMeerkats')
                    ->numeric(),
                TextEntry::make('hasCubs')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('hasScouts')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('hasRovers')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('hasBranch1')
                    ->numeric(),
                TextEntry::make('hasBranch2')
                    ->numeric(),
                TextEntry::make('hasBranch3')
                    ->numeric(),
                TextEntry::make('hasBranch4')
                    ->numeric(),
                TextEntry::make('hasBranch5')
                    ->numeric(),
                TextEntry::make('sendWeeklyMails')
                    ->numeric(),
                TextEntry::make('assoc_to_district')
                    ->numeric(),
                TextEntry::make('assoc_to_region')
                    ->numeric(),
                TextEntry::make('roverAssocToGroup')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('phys_address')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('postalAddress')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('postalCountryID')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('phys_country_id')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('bankingDetails')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('bankAccountName')
                    ->placeholder('-'),
                TextEntry::make('bankName')
                    ->placeholder('-'),
                TextEntry::make('branchName')
                    ->placeholder('-'),
                TextEntry::make('branchCode')
                    ->placeholder('-'),
                TextEntry::make('bankAccountNumber')
                    ->placeholder('-'),
                TextEntry::make('invoiceNotes')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('facebook')
                    ->placeholder('-'),
                TextEntry::make('twitter')
                    ->placeholder('-'),
                TextEntry::make('website')
                    ->placeholder('-'),
                TextEntry::make('email')
                    ->label('Email address')
                    ->placeholder('-'),
                TextEntry::make('googleplus')
                    ->placeholder('-'),
                TextEntry::make('instagram')
                    ->placeholder('-'),
                TextEntry::make('linkedin')
                    ->placeholder('-'),
                TextEntry::make('pintrest')
                    ->placeholder('-'),
                TextEntry::make('youtube')
                    ->placeholder('-'),
                TextEntry::make('tumblr')
                    ->placeholder('-'),
                TextEntry::make('googleMaps')
                    ->placeholder('-'),
                TextEntry::make('gpsLat')
                    ->placeholder('-'),
                TextEntry::make('gpsLon')
                    ->placeholder('-'),
                TextEntry::make('created')
                    ->dateTime(),
                TextEntry::make('createdby')
                    ->numeric(),
                TextEntry::make('modified')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('modifiedby')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('active')
                    ->numeric(),
                TextEntry::make('weatherID')
                    ->placeholder('-'),
                TextEntry::make('weatherLocationName')
                    ->placeholder('-'),
                TextEntry::make('managedRegionally')
                    ->numeric(),
                TextEntry::make('canMoveToEntsha')
                    ->numeric(),
                TextEntry::make('using20')
                    ->numeric(),
                TextEntry::make('groupRegNr')
                    ->placeholder('-'),
                TextEntry::make('censusDone')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('groupLastUpdated')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('groupLastUpdatedBy')
                    ->numeric()
                    ->placeholder('-'),
            ]);
    }
}
