<?php

namespace App\Filament\Admin\Resources\SystemUserTypes\Schemas;

use Filament\Forms\Components\DateTimePicker;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Schema;

class SystemUserTypeForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('countryID')
                    ->required()
                    ->numeric()
                    ->default(196),
                TextInput::make('name')
                    ->required(),
                Textarea::make('description')
                    ->required()
                    ->columnSpanFull(),
                TextInput::make('sysAdmin')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('nationalRole')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('regionalRole')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('superDistrictRole')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('districtRole')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('groupRole')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('denRole')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('packRole')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('troopRole')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('crewRole')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('adultLeaderRole')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('parentHelperRole')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('alumniRole')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('warrantedRole')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('appointmentRole')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('requiresCriminalClearance')
                    ->required()
                    ->numeric()
                    ->default(1),
                TextInput::make('signsLeft')
                    ->numeric(),
                TextInput::make('signsRight')
                    ->numeric(),
                TextInput::make('chargeRole')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('active')
                    ->required()
                    ->numeric()
                    ->default(1),
                TextInput::make('position')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canAdminAlumni')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canSeeAlumni')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canAdminNational')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canSeeNational')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canAdminRegion')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canSeeRegion')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canAdminRegionKids')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canAdminRegionTraining')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canAdminSuperDistrict')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canSeeSuperDistrict')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canAdminDistrict')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canSeeDistrict')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canAdminDistrictKids')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canAdminGroup')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canSeeGroup')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canAdminGroupAdults')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canAwardGroupMeerkats')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canAwardGroupCubs')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canAwardGroupScouts')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canAwardGroupRovers')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canSeeSupport')
                    ->required()
                    ->numeric()
                    ->default(1),
                TextInput::make('canAdminSupport')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canAddWarrants')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canAdminProperty')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canSignWarrants')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canAdminForm29')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('canAdminPoliceClearance')
                    ->required()
                    ->numeric()
                    ->default(0),
                DateTimePicker::make('created')
                    ->required(),
                TextInput::make('createdby')
                    ->required()
                    ->numeric()
                    ->default(1),
                DateTimePicker::make('modified'),
                TextInput::make('modifiedby')
                    ->numeric(),
            ]);
    }
}
